### PR TITLE
simplify rating directive

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by IgorMinar** [comment]
just a dirty commit with some changes I'd like to propose. the paginate directive needs to be changed as well to reflect these changes. I started working on that one.

**Comment by IgorMinar** [comment]
btw I noticed that there isn't a good documentation/specification for each of the components. could you please work on that?

**Comment by pkozlowski-opensource** [comment]
@IgorMinar wow, cool, your version is much simpler, going to rework rating / pagination based on the above.

**Comment by pkozlowski-opensource** [comment]
@IgorMinar I've pushed simplified version of the rating directive based on your input: a599e46b83e79f57c0bf6c0453e0e977e6c7eb5a. I didn't incorporate all of the suggestions due to various reasons, see my comments in your PR, but we can surely do another iteration on this one.

**Comment by pkozlowski-opensource** [comment]
@IgorMinar reworked pagination as well, new version landed as edd46ede9afd0cbded92b868bf2ff6c752a90982. It is simpler / better tested now.

**Pull request closed without merging**
